version: '3.7'

services:
    ticket-world-mysql:
        image: mysql:8.0.35
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - ticket-world-mysql:/var/lib/mysql

volumes:
    ticket-world-mysql:
