version: '3.7'

services:
    ticket-world-spring:
        build:
            context: .
            dockerfile: web-api.dockerfile
        ports:
            - "8080:8080"
        expose:
            - "8080"
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: 2GB
        environment:
            NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        networks:
            - monitoring_net

#    agent:
#        container_name: newrelic-infra
#        build:
#            context: ./newrelic
#            dockerfile: newrelic-infra.dockerfile
#        cap_add:
#            - SYS_PTRACE
#        pid: host
#        privileged: true
#        volumes:
#            - "/:/host:ro"
#            - "/var/run/docker.sock:/var/run/docker.sock"
#        restart: unless-stopped
#        environment:
#            NRIA_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
#        networks:
#            - monitoring_net

networks:
    monitoring_net:
        external: true
