version: '3.7'

services:
    ticket-world-mysql:
        image: mysql:8.0.35
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: 2GB
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - ticket-world-mysql:/var/lib/mysql
        networks:
            - monitoring_net

    ticket-world-mysql-exporter:
        image: prom/mysqld-exporter
        ports:
            - "9104:9104"
        depends_on:
            -   ticket-world-mysql
        command:
            - "--mysqld.username=${MYSQL_USER}:${MYSQL_PASSWORD}"
            - "--mysqld.address=ticket-world-mysql:3306"
        networks:
            - monitoring_net

volumes:
    ticket-world-mysql:

networks:
    monitoring_net:
        external: true
