spring:
    datasource:
        url: jdbc:mysql://{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}?serverTimezone=Asia/Seoul
        username: {MYSQL_USERNAME}
        password: {MYSQL_PASSWORD}
kopis:
    api:
        key: {KOPIS_API_KEY}
        base-url: {KOPIS_API_BASE_URL}
